# Generated by Django 2.2 on 2020-12-07 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='content',
        ),
    ]
